bindata/v3.11.0/kube-scheduler/deployment.yaml, manifests/0000_11_cluster-kube-scheduler-operator_06_deployment.yaml, pkg/operator/v311_00_assets/bindata.go
=> Run kube-scheduler and its operator on masters.

hack/update-generated-bindata.sh, hack/verify-generated-bindata.sh
Fix bin generated files, previously we were pointing to v3.10 assets which would have failed.
=> Fix verify generated bin data script

OWNERS
@aveshagarwal I promise to never tag anything that will in any way alter how scheduler is deployed or its config, but it seems practical to have somebody to lgtm syncs like 
https://github.com/openshift/cluster-kube-scheduler-operator/pull/18 on this side of this planet :-)
=> add mfojtik to owners

cmd/cluster-kube-scheduler-operator/render/render.go
Trimmed version of https://github.com/openshift/cluster-kube-scheduler-operator/pull/17 with just the override changes.
/cc @sttts
=> render: remove --config-override-file default and pluralize

pkg/operator/v311_00_assets/bindata.go
Issue from https://github.com/openshift/cluster-kube-scheduler-operator/pull/21 to update auto generated bin data.
@sjenning @sttts
=> Fix auto generated bin data.

manifests/0000_11_cluster-kube-scheduler-operator_00_namespace.yaml, manifests/0000_11_cluster-kube-scheduler-operator_03_configmap.yaml, manifests/0000_11_cluster-kube-scheduler-operator_04_clusterrolebinding.yaml, manifests/0000_11_cluster-kube-scheduler-operator_05_serviceaccount.yaml, manifests/0000_11_cluster-kube-scheduler-operator_06_deployment.yaml, pkg/operator/starter.go
=> Move scheduler operator to its own namespace.

Makefile
=> Add e2e place holder and fix make verify.

hack/verify-codegen.sh
=> Do not use `cp -a` as it fails inside container.

bindata/v3.11.0/kube-scheduler/pod.yaml, manifests/0000_11_cluster-kube-scheduler-operator_06_deployment.yaml, pkg/operator/v311_00_assets/bindata.go
=> Add priority class to static scheduler pod and its operator pods.

OWNERS
Avesh, adding myself to owners file.
/cc @aveshagarwal
=> Add ravi to owners

OWNERS
Adding Stefan and Seth to owners.
=> Add Seth/Stefan to owners

bindata/bootkube/config/bootstrap-config-overrides.yaml, bindata/bootkube/config/config-overrides.yaml, bindata/v3.11.0/kube-scheduler/defaultconfig-postbootstrap-with-policy.yaml, bindata/v3.11.0/kube-scheduler/defaultconfig-postbootstrap.yaml, bindata/v3.11.0/kube-scheduler/defaultconfig.yaml, pkg/operator/v311_00_assets/bindata.go
fixes #63 
@ravisantoshgudimetla
=> move from componentconfig/v1alpha1 to kubescheduler.config.k8s.io/v1alpha1

bindata/v3.11.0/kube-scheduler/pod.yaml, manifests/0000_11_kube-scheduler-operator_06_deployment.yaml, pkg/operator/target_config_reconciler_v311_00.go, pkg/operator/v311_00_assets/bindata.go
Switch the image pull policy from `Always` to `IfNotPresent`
=> switch to pull if not present from always

pkg/operator/starter.go, pkg/operator/target_config_reconciler.go, pkg/operator/target_config_reconciler_v311_00.go
This helps in getting policy configmap name from api instead of using hardcoded `policy-configmap`.
=> Switch to getting policy configmap name from api

manifests/0000_11_kube-scheduler-operator_03_version-mapping.yaml, manifests/0000_11_kube-scheduler-operator_06_deployment.yaml, manifests/0000_11_kube-scheduler-operator_07_clusteroperator.yaml
https://github.com/openshift/cluster-kube-apiserver-operator/pull/308
@deads2k @derekwaynecarr
=> minor fitting to set versions for our operator

bindata/bootkube/bootstrap-manifests/kube-scheduler-pod.yaml, bindata/v3.11.0/kube-scheduler/pod.yaml, pkg/operator/v311_00_assets/bindata.go
=> kube-scheduler: config authnz settings

pkg/operator/target_config_reconciler_v311_00.go, pkg/operator/target_config_reconciler_v311_00_test.go
Make sure featuregates are sorted
=> Fix sorting in featuregates

glide.lock, pkg/operator/target_config_reconciler_v311_00_test.go, vendor/github.com/openshift/api/config/v1/types_feature.go, vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
this helps with upgrade timing because save one minute on the lease.
=> speed up leader election

bindata/v3.11.0/kube-scheduler/pod.yaml, pkg/operator/v311_00_assets/bindata.go
Will close #108 once this passes
=>  Change one of the ports to be checked to 10259 

manifests/0000_25_kube-scheduler-operator_06_deployment.yaml
Not that this effects anything but I noticed some whitespaces, removing them.
=> remove whitespaces

manifests/0000_25_kube-scheduler-operator_02_operator.cr.yaml
Same changes as https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/100
=> Remove old values from operator config CR

pkg/operator/target_config_reconciler_v311_00.go
Small refactor to handle some edge cases.
/cc @deads2k
=> Small refactor

test/e2e/main_test.go, test/e2e/scheduler_test.go
E2e test framework for policy configmap validation
/cc @sjenning
=> Test to check scheduler configmap working or not

pkg/operator/starter.go, pkg/operator/target_config_reconciler.go, pkg/operator/target_config_reconciler_v311_00.go
Fix operator status, so that we don't enter into permanent degrade status.
/cc @deads2k @sjenning
=> Fix operator status

Dockerfile, Dockerfile.rhel7
=> Switch to go 1.12

README.md
Add a readme for kube-scheduler operator
/cc @damemi
=> Add scheduler readme

OWNERS
=> Add Mike to reviewers list

pkg/operator/target_config_reconciler.go, pkg/operator/target_config_reconciler_v311_00.go
Remove unnecessary dead code from kube-scheduler-operator
/cc @damemi
=> Clean up dead code

OWNERS
Adds me, Maciej, and Jan to owners as reviewers/approvers
=> Update OWNERS file to add new reviewers/approvers

bindata/bootkube/bootstrap-manifests/kube-scheduler-pod.yaml
Counter part to https://github.com/openshift/installer/pull/2275.
=> bootstrap: log to /var/log/bootstrap-control-plane/kube-scheduler.log

pkg/operator/resourcesynccontroller/resourcesynccontroller.go
=> Bug 1745671: use cached clients in resource syncer

Dockerfile, Dockerfile.rhel7, Makefile
=> Fix makefile to allow make images to work

manifests/0000_90_kube-scheduler-operator_03_servicemonitor.yaml, pkg/operator/configmetrics/configmetrics.go
=> Bug 1749457: match servicemonitor label with actual label on service

pkg/operator/starter.go, pkg/operator/target_config_reconciler.go, pkg/operator/target_config_reconciler_v410_00.go
=> Switch to genericoperatorclient

Makefile, manifests/0000_25_kube-scheduler-operator_01_config.crd.yaml
This depends on https://github.com/openshift/library-go/pull/521 to include crd-schema-gen
=> Use new crd-gen makefile targets from library-go

manifests/0000_90_kube-scheduler-operator_03_servicemonitor.yaml
https://github.com/openshift/cluster-monitoring-operator/pull/516
=> move KubeSchedulerDown alert to this operator

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiextensions.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiregistration.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apps.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/json_patch_helpers.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go, vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go, vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go, vendor/modules.txt
Fixes logging that got broken in file observer.
=> bump(*): library-go

manifests/0000_90_kube-scheduler-operator_04_servicemonitor-scheduler.yaml, pkg/operator/starter.go
=> Bug 1735509: monitoring: move service monitor RBAC rules to manifests/

OWNERS
=> remove sjenning from OWNERS

Dockerfile.rhel7
backport of https://github.com/openshift/cluster-kube-scheduler-operator/pull/214
/cc @soltysh @bparees
=> [release-4.4] Bug 1810182: Remove wildcard COPY form Dockerfile

Dockerfile.rhel7
It doesn't work with docker and buildah, only image builder.
/cc @soltysh @bparees
=> Bug 1810181: Remove wildcard COPY form Dockerfile

pkg/operator/starter.go, pkg/operator/target_config_reconciler.go, pkg/operator/target_config_reconciler_v410_00.go
/assign @deads2k
Picks openshift/cluster-kube-apiserver-operator#729 and openshift/cluster-kube-apiserver-operator#726 to ks-o and also I renamed the files so it's easier to bring changes between operators. 
/hold
for 4.5
=> Switch to staticresource control loop

bindata/v4.1.0/kube-scheduler/pod.yaml, pkg/operator/v410_00_assets/bindata.go
=> Set default container for oc logs

bindata/v4.1.0/kube-scheduler/pod.yaml, pkg/operator/v410_00_assets/bindata.go
=> [release-4.3] Bug 1822770: Normalize CPU requests on masters

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/config/clusteroperator/v1helpers/status.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/bindata/bindata.go, vendor/modules.txt
=> Bug 1813894: Stop using service ca from service account token

pkg/operator/configmetrics/configmetrics.go
This adds a boolean `cluster_legacy_scheduler_policy` metric that reports whether the operator is trying to use a legacy `Policy` config to customize the scheduler configuration
This also changes the operator's metric's FQName to `cluster_kube_scheduler_operator` now that there are multiple metrics it's reporting.
=> Bug 1840173: Add boolean metric to report legacy policy config

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go, vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling.go, vendor/github.com/openshift/library-go/pkg/crypto/crypto.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apps.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/bindata/bindata.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/bindata/bindata.go, vendor/modules.txt
Includes the changes from https://github.com/openshift/library-go/pull/821
=> [release-4.3] Bug 1848583: bump(library-go): Add resource requests to installer/pruner pods

Dockerfile.rhel7, go.mod, go.sum, vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk, vendor/modules.txt
requires:
/cc @damemi @ingvagabund
=> Fix golang version to follow kube 1.19

bindata/v4.1.0/kube-scheduler/kubeconfig-cm.yaml, pkg/operator/configobservation/configobservercontroller/observe_config_controller.go, pkg/operator/configobservation/interfaces.go, pkg/operator/starter.go, pkg/operator/targetconfigcontroller/targetconfigcontroller.go, pkg/operator/v410_00_assets/bindata.go
This fixes webhooks and anything else that didn't have the patch for the override. It also makes the intention clearer in the kubeconfig with the actual URL there.
/cc @soltysh @deads2k
=> Bug 1879019: Explicitly use internal LB for KS

manifests/0000_90_kube-scheduler-operator_03_servicemonitor.yaml, manifests/0000_90_kube-scheduler-operator_04_servicemonitor-scheduler.yaml
This is matches openshift/enhancements#510 and doesn't change existing behavior
=> add current profile annotations to CVO manifests

bindata/v4.1.0/kube-scheduler/pod.yaml, cmd/cluster-kube-scheduler-operator/main.go, pkg/cmd/recoverycontroller/cmd.go, pkg/operator/resourcesynccontroller/resourcesynccontroller.go, pkg/operator/v410_00_assets/bindata.go
backporting:
- https://github.com/openshift/cluster-kube-scheduler-operator/pull/288
- https://github.com/openshift/cluster-kube-scheduler-operator/pull/311
/cc @soltysh
=> Bug 1903586: Sync new kube-scheduler-client-cert-key on recovery

bindata/v4.1.0/kube-scheduler/pod.yaml, cmd/cluster-kube-scheduler-operator/main.go, pkg/cmd/recoverycontroller/cmd.go, pkg/operator/resourcesynccontroller/resourcesynccontroller.go, pkg/operator/v410_00_assets/bindata.go
backport of https://github.com/openshift/cluster-kube-scheduler-operator/pull/315
/cc @soltysh
=> Bug 1915363: Sync new kube-scheduler-client-cert-key on recovery

OWNERS
=> Remove tnozicka and ravi from OWNERS

pkg/operator/targetconfigcontroller/targetconfigcontroller.go
The operator must currently observe configmaps in the target namespace, however some (like leader-election) update frequently, triggering event handling in the targetConfigController and this log message to be printed every ~3s.
Moving it to only be logged on actual updates to the relevant policy configmap (and by extension the scheduler pod itself) will limit how often this is logged.
The alternative to this was changing the controller's event handlers to ignore updates from certain specific resources, but that leads to too many edge cases and the likelihood of regression if new targetNamespace resources are added.
=> Bug 1926579: Move warning about deprecated spec.policy field

go.mod, go.sum, vendor/github.com/gogo/protobuf/proto/text_parser.go, vendor/golang.org/x/sync/singleflight/singleflight.go, vendor/modules.txt
Fixes https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3121
=> bug 1934154: Bump github.com/gogo/protobuf to v1.3.2

manifests/0000_25_kube-scheduler-operator_06_deployment.yaml
To conform to https://github.com/openshift/enhancements/blob/master/CONVENTIONS.md#resources-and-limits
=> bug 1938468: Specify cpu resource request for kube-scheduler-operator-container container

go.mod, go.sum, vendor/github.com/gogo/protobuf/proto/text_parser.go, vendor/golang.org/x/sync/singleflight/singleflight.go, vendor/modules.txt
Fixes https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3121
=> bug 1924490: Bump github.com/gogo/protobuf to v1.3.2

README.md
=> bug 1949364: Mention scheduling profiles

manifests/0000_90_kube-scheduler-operator_03_servicemonitor.yaml
Follow up for https://github.com/openshift/cluster-kube-scheduler-operator/pull/361
=> SchedulerLegacyPolicySet: add 60 min wait

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/resource_cache.go, vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go, vendor/modules.txt
Bumping the library-go dependency to the latest. It brings performance improvements in this [PR](https://github.com/openshift/library-go/pull/1235).
=> Upgrade library-go version

pkg/operator/starter.go
Running in my cluster (after deploying the scheduler operator with the changes)
```
NAME                                                                  READY   STATUS    RESTARTS   AGE
openshift-kube-scheduler-ip-10-0-144-236.us-east-2.compute.internal   3/3     Running   0          13m
openshift-kube-scheduler-ip-10-0-169-240.us-east-2.compute.internal   3/3     Running   0          15m
openshift-kube-scheduler-ip-10-0-227-47.us-east-2.compute.internal    3/3     Running   0          55s
NAME                                                                        READY   STATUS    RESTARTS   AGE
openshift-kube-scheduler-guard-ip-10-0-144-236.us-east-2.compute.internal   1/1     Running   0          94s
openshift-kube-scheduler-guard-ip-10-0-169-240.us-east-2.compute.internal   1/1 …
```
=> bug 2005901: Guard controller pdb

go.mod, go.sum, pkg/operator/starter.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go, vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go, vendor/modules.txt
To brings changes introduced in https://github.com/openshift/library-go/pull/1281
=> bug 2005901: Bump library-go

bindata/assets/kube-scheduler/pod.yaml, pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_1.yaml, pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_2.yaml, pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_3.yaml
=> Bug 2040132: drop --port flag

go.mod, go.sum, pkg/operator/starter.go, vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go, vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go, vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go, vendor/github.com/openshift/library-go/test/library/metrics/query.go, vendor/modules.txt
To pick up https://github.com/openshift/library-go/pull/1287
/hold
=> bug 2005901: Sync the library-go

bindata/assets/kube-scheduler/pod.yaml, pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_1.yaml, pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_2.yaml, pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_3.yaml
Replaces deprecated annotation with newer replacement.
/assign @soltysh
=> Bug 2035986: Replace deprecated annotation

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodfallback/static_pod_fallback_condition.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go, vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go, vendor/modules.txt
bringing in openshift/library-go#1300
=> bug 2029470: update library-go to get rapid installer pod fixes

bindata/assets/kube-scheduler/svc.yaml, manifests/0000_25_kube-scheduler-operator_02_service.yaml
service-ca-operator uses newer annotations @soltysh
=> update cert injection annotations to beta

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodfallback/static_pod_fallback_condition.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go, vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go, vendor/modules.txt
picking up openshift/library-go#1302
pick of https://github.com/openshift/cluster-kube-scheduler-operator/pull/407 for 4.10
=> bug 2053148: [release-4.10] update library-go to get rapid installer pod fixes

README.md
=> bug 2064024: README: fix scheduler configuration formatting

Makefile, bindata/config_test.go, go.mod
Unit test which checks if the bootstrap config and the controlplane config are in sync or not. This helps in reducing the problems like 
https://bugzilla.redhat.com/show_bug.cgi?id=2062459
=> Bug 2062459: Introduce sync unit test

.ci-operator.yaml, Dockerfile.rhel7, go.mod, go.sum
Replaces https://github.com/openshift/cluster-kube-scheduler-operator/pull/431
=> Updating ose-cluster-kube-scheduler-operator images to be consistent with ART

.ci-operator.yaml, Dockerfile.rhel7, go.mod, go.sum
Supersedes https://github.com/openshift/cluster-kube-scheduler-operator/pull/426
=> bug 2117746: Updating ose-cluster-kube-scheduler-operator images to be consistent with ART

README.md
=> Describe how to increase log level of kube-scheduler instances

bindata/bootkube/bootstrap-manifests/kube-scheduler-pod.yaml
Similar to https://github.com/openshift/cluster-kube-controller-manager-operator/pull/660
Copy-pasting the requests from https://github.com/openshift/cluster-kube-scheduler-operator/blob/master/bindata/assets/kube-scheduler/pod.yaml
=> bootstrap-kube-scheduler: specify resources.requests

bindata/bootkube/bootstrap-manifests/kube-scheduler-pod.yaml
Backporting https://github.com/openshift/cluster-kube-scheduler-operator/pull/445
=> OCPBUGS-4292: bootstrap-kube-scheduler: specify resources.requests

bindata/bootkube/bootstrap-manifests/kube-scheduler-pod.yaml
Backporting https://github.com/openshift/cluster-kube-scheduler-operator/pull/445
=> OCPBUGS-4294: bootstrap-kube-scheduler: specify resources.requests

bindata/bootkube/bootstrap-manifests/kube-scheduler-pod.yaml, go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/assets/assets.go, vendor/github.com/openshift/library-go/pkg/operator/render/options/generic.go, vendor/github.com/openshift/library-go/pkg/operator/render/render.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go, vendor/modules.txt
Backporting https://github.com/openshift/cluster-kube-scheduler-operator/pull/446
=> OCPBUGS-4478: Sync library go 4.12

manifests/0000_90_kube-scheduler-operator_04_servicemonitor-scheduler.yaml
Added client certificates based on https://github.com/deads2k/openshift-enhancements/blob/master/enhancements/monitoring/client-cert-scraping.md
=> Add client certificate and key to service monitor

go.mod, go.sum, pkg/operator/starter.go, vendor/github.com/openshift/library-go/pkg/crypto/crypto.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/manifests/guard-pod.yaml, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go, vendor/modules.txt
Backporting https://github.com/openshift/cluster-kube-scheduler-operator/pull/459
=> OCPBUGS-7369: Guard controller: set the readiness probe endpoint explicitly

go.mod, go.sum, pkg/operator/starter.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/manifests/guard-pod.yaml, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go, vendor/modules.txt
Backporting https://github.com/openshift/cluster-kube-scheduler-operator/pull/462
=> OCPBUGS-7756: Guard controller: set the readiness probe endpoint explicitly

go.mod, go.sum, pkg/operator/starter.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/bindata/bindata.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go, vendor/modules.txt
Backporting https://github.com/openshift/cluster-kube-scheduler-operator/pull/464
=> OCPBUGS-8235: Guard controller: set the readiness probe endpoint explicitly

bindata/assets/config/defaultconfig.yaml, bindata/bootkube/config/bootstrap-config-overrides.yaml
Manually picked https://github.com/openshift/cluster-kube-scheduler-operator/pull/476
/assign @tkashem
=> OCPBUGS-7785: migrate to using lease objects for leader election

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/operator/render/options/generic.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go, vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go, vendor/modules.txt
=> OCPBUGS-14323: Change manifest directory permissions

manifests/0000_90_kube-scheduler-operator_03_servicemonitor.yaml
=> OCPBUGS-14052: KubeSchedulerDown: set runbook_url annotation

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go, vendor/modules.txt
This PR is a manual cherry-pick of these 3 PRs;
* https://github.com/openshift/library-go/pull/1570
* https://github.com/openshift/library-go/pull/1536
* https://github.com/openshift/library-go/pull/1546
=> [release-4.12] OCPBUGS-19837: Update staticpod file permissions to conform with CIS benchmarks

README.md
=> NO-JIRA: README.md: steps for enabling profiling, collecting heap and running go tool pprof

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go, vendor/modules.txt
=> TRT-1420: Bump openshift/library-go to pick up revision_controller revert

.snyk
=> OCPBUGS-23631: Add .snyk file to exclude vendor and ignore unit tests

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/crypto/crypto.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/manifests/guard-pod.yaml, vendor/github.com/openshift/library-go/pkg/operator/status/condition.go, vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go, vendor/modules.txt
Pulling https://github.com/openshift/library-go/pull/1602
=> OCPBUGS-27022: bump(library-go)=release-4.14

README.md
=> NO-JIRA: README: add notes about dumping KS's node cache

README.md
=> NO-JIRA: readme: describe mapping between logLevel and log level

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go, vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go, vendor/modules.txt
Syncing with https://github.com/openshift/library-go/pull/1682
=> WRKLDS-1071: bump(library-go)=release-4.16

Dockerfile.ocp
test with https://github.com/openshift/api/pull/2030
=> create CRDs from openshift/api

.ci-operator.yaml, Dockerfile.ocp, go.mod, pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
On top of https://github.com/openshift/cluster-kube-scheduler-operator/pull/565.
=> OCPBUGS-57855: Updating ose-cluster-kube-scheduler-operator-container image to be consistent with ART for 4.20
