- cmd/cluster-kube-scheduler-operator/render/render.go
Without this we would get errors if predicates passed are nil
```
docker run -v $(pwd)/tls:/assets --rm openshift/origin-cluster-kube-scheduler-operator:latest /usr/bin/cluster-kube-scheduler-operator render --asset-input-dir=/assets --asset-output-dir=/assets/kube-scheduler-bootstrap --config-output-file=/assets/kube-scheduler-bootstrap/config --config-override-file=/usr/share/bootkube/manifests/config/config-overrides.yaml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6c68e8]
goroutine 1 [running]:
github.com/openshift/cluster-kube-scheduler-operator/vendor/github.com/openshift/library-go/pkg/assets.LoadFilesRecursively.func1(0xc4205bed70, 0x4c, 0x170be60, 0xc4202185b0, 0x0, 0x0, 0x17, 0xc420117500) …
```
> Fix nil pointer

- bindata/bootkube/manifests/kube-system-kube-scheduler-config.yaml
- bindata/v3.11.0/kube-scheduler/cm.yaml
- bindata/v3.11.0/kube-scheduler/deployment.yaml
- hack/update-generated-bindata.sh
The kube-scheduler-config configmap created by the render command will live in kube-system, next to the phase-2 daemonset.
The config of phase-3 is supposed to be created by the operator (called `cm.yaml` in the other control plane component operators).
> Unify kube-scheduler-config configmap names

- bindata/v3.11.0/kube-scheduler/pod.yaml
- pkg/operator/v311_00_assets/bindata.go
One in a series of PRs to set memory requests for all control plane and high memory use components.
We are encountering master instability (https://github.com/openshift/installer/pull/408 https://github.com/openshift/installer/pull/785) as the number of components increase because many components run `BestEffort` giving the scheduler no information on pod resource usage.
On a steady state empty cluster, `kube-scheduler` uses 35MB.
{pod_name="openshift-kube-scheduler-dev-master-0"} | 34770944
Because it is a control plane component, I'm giving it a buffer and setting to `50Mi`
@aveshagarwal @derekwaynecarr
> bindata: add memory request to kube-scheduler pod

- manifests/0000_11_cluster-kube-scheduler-operator_06_deployment.yaml
Follow on to the previous PR #42 setting memory limit for the operator pod.
{pod_name="openshift-cluster-kube-scheduler-operator-74879b869b-qwbts"}	29687808
Uses 30Mi in practice. Setting to `50Mi` for some buffer.
> manifests: add memory request to operator pod

- Makefile
- test/e2e/main_test.go
> Add an e2e test for verifying that cluster-kube-scheduler-operator deployment is up.

- cmd/render/render.go
That's not needed anymore for long time (was only temporariy for a transition of the bootstrap phase).
Blocked by https://github.com/openshift/installer/pull/1091.
> Remove disablephase2 flag.

- manifests/0000_11_kube-scheduler-operator_07_clusteroperator.yaml
- pkg/operator/starter.go
rename cluster operator resource to not stutter by
- dropping the openshift prefix
- dropping the operator suffix
/cc @sjenning @ravisantoshgudimetla @deads2k
> update clusteroperator name to kube-scheduler

- pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
While looking into a network deployment failure that might have been caused by a openshift-kube-scheduler-operator failure, I found this in the scheduler operator logs:
```
E0219 09:26:48.743792       1 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/src/github.com/openshift/cluster-kube-scheduler-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/go/src/github.com/openshift/cluster-kube-scheduler-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/github.com/openshift/cluster-kube-scheduler-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:573
/usr/local/go/src/runtime/panic.go:502 …
```
> Don't pass nil function pointer to NewConfigObserver

- bindata/v3.11.0/kube-scheduler/operator-config.yaml
- pkg/operator/operatorclient/operatorclient.go
- pkg/operator/starter.go
- pkg/operator/target_config_reconciler.go
- pkg/operator/v311_00_assets/bindata.go
Switching the kubescheduler type name from `instance` to `cluster`.
/cc @deads2k
> Change kubescheduler type name from instance to cluster

- bindata/v3.11.0/kube-scheduler/policyconfigmap-role.yaml
- bindata/v3.11.0/kube-scheduler/policyconfigmap-rolebinding.yaml
- pkg/operator/resourcesynccontroller/resourcesynccontroller.go
- pkg/operator/starter.go
- pkg/operator/target_config_reconciler.go
- pkg/operator/target_config_reconciler_v311_00.go
- pkg/operator/v311_00_assets/bindata.go
This PR adds
- RBAC for `system:kube-scheduler` user to access configmaps in `openshift-kube-scheduler` namespace. This was not an issue before #62 merged but after that we have to add following roles/rolebindings.
/cc @sjenning 
We are able to pick up configmap changes now.
`I0321 23:06:23.187561       1 factory.go:1118] Creating scheduler from configuration: {{ } [{PodFitsHostPorts <nil>} {PodFitsResources <nil>} {NoDiskConflict <nil>} {NoVolumeZoneConflict <nil>} {MatchNodeSelector <nil>} {HostName <nil>}] [{LeastRequestedPriority 1 <nil>} {BalancedResourceAllocation 1 <nil>} {ServiceSpreadingPriority 1 <nil>} {EqualPriority 1 <nil>}] [] 0 false}
`
We can see above line in kube-scheduler logs.
> Policy configmap working with kube-scheduler

- bindata/bootkube/bootstrap-manifests/kube-scheduler-pod.yaml
- bindata/v3.11.0/kube-scheduler/pod.yaml
- pkg/operator/v311_00_assets/bindata.go
this will help land the rebase.  The secure option fails to bootstrap.
> force scheduler insecure

- bindata/bootkube/bootstrap-manifests/kube-scheduler-pod.yaml
- bindata/v3.11.0/kube-scheduler/pod.yaml
- pkg/operator/v311_00_assets/bindata.go
Due to https://github.com/kubernetes/kubernetes/pull/69884.
> Set cert-dir to prepare for 1.13

- bindata/bootkube/bootstrap-manifests/kube-scheduler-pod.yaml
- bindata/v3.11.0/kube-scheduler/pod.yaml
- bindata/v3.11.0/kube-scheduler/svc.yaml
- pkg/operator/v311_00_assets/bindata.go
This is blocked by https://github.com/openshift/cluster-monitoring-operator/blob/172beb3e0d2cbf1f79bf61ba9c3f5bea373b4125/assets/prometheus-k8s/service-monitor-kube-scheduler.yaml#L15 pointing to the secure port.
> Disable insecure port

- pkg/operator/target_config_reconciler_v311_00.go
I've observed a panic from this line for logging that stopped my cluster from starting.
> prevent panic in logging message

- pkg/operator/starter.go
- pkg/operator/target_config_reconciler.go
- pkg/operator/target_config_reconciler_v311_00.go
- pkg/operator/target_config_reconciler_v311_00_test.go
I was initially thinking of using config observer pattern to list feature gates and update kube-scheduler but later realized that we are updating any config related to kube-scheduler here but just updating one of the flags, so I have updated the target_config_reconciler.go. I haven't tested this locally.
> Get feature gates and using them while starting kube-scheduler

- pkg/operator/starter.go
- pkg/operator/target_config_reconciler_v311_00.go
Counterpart of https://github.com/openshift/cluster-kube-controller-manager-operator/pull/221. This is needed for monitoring to be able to verify the serving cert. Without this PR, only the self-signed cert is used by kube-scheduler.
> pod.yaml: wire serving-cert secret

- bindata/v3.11.0/kube-scheduler/pod.yaml
- manifests/0000_90_kube-scheduler-operator_03_servicemonitor.yaml
- pkg/operator/target_config_reconciler_v311_00.go
- pkg/operator/v311_00_assets/bindata.go
Add an init container so that we wait for 10259 port to be available before throwing error.
/cc @deads2k @sjenning @sttts
> Wait for port to be available

- Dockerfile
- Dockerfile.rhel7
Some of the gofmts might fail. Will create separate PRs to address them.
https://github.com/openshift/cluster-kube-apiserver-operator/pull/414
> Switch to go 1.11

- manifests/0000_11_kube-scheduler-operator_02_operator.cr.yaml
- pkg/operator/starter.go
- pkg/operator/v311_00_assets/bindata.go
Switch away from using EnsureOperatorConfigExists, which is being removed in favor of CVO management of operator resources
> Use the CVO for operator config

- bindata/bootkube/manifests/00_openshift-kube-scheduler-ns.yaml
- bindata/v3.11.0/kube-scheduler/ns.yaml
- manifests/0000_11_kube-scheduler-operator_00_namespace.yaml
- pkg/operator/v311_00_assets/bindata.go
**Why this change?**
When https://github.com/openshift/cluster-kube-apiserver-operator/pull/394 merges, all the pods running openshift cluster will have a [defaultNodeSelector](https://docs.openshift.com/container-platform/3.11/admin_guide/managing_projects.html#setting-the-cluster-wide-default-node-selector) if it has been set by cluster-admin including pods running in `openshift-*` namespace. The main advantage of having that feature is in a multi-tenant environment, any new project created can be steered towards compute nodes(non-master nodes).
**What should I do?**
If you think, the pods in your namespace shouldn't have defaultNodeSelector set, please review this PR. If not feel free to close this. The annotation added as part of this PR lets all the pods created within your project …
> Add node-selector annotation to namespace

- manifests/0000_25_kube-scheduler-operator_06_deployment.yaml
@deads2k @mfojtik @ravisantoshgudimetla 
avoids the `Operator log level changed from "Debug" to "Normal"` event on KSO restart, since the logging controller defaults an empty loglevel to be `Normal` or `2`.
also see
https://github.com/openshift/library-go/pull/375
> change initial loglevel to align with logging controller defaults

- manifests/0000_25_kube-scheduler-operator_06_deployment.yaml
As of now, because of infinite tolerations against all the possible taints, we are seeing that operators are not getting evicted from nodes that have `NoExecute` taint on them. This PR tightens the conditions around which can be pods can be scheduled/evicted. The downside is there is a very good chance that pods would be evicted from nodes that have certain conditions like `disk-pressure`, `memory-pressure`, taints added by other controllers(operators) etc. So, please make sure that this change is ok with your operator/operand before merging this PR.
/cc @sjenning @smarterclayton
> Bug 1705649 : Cluster with halted master did not reschedule operators after 5m of being down

- pkg/operator/staleconditions/remove_stale_conditions.go
- pkg/operator/starter.go
- test/e2e/scheduler_test.go
Built on top of #142. 
@deads2k Added a e2e test which verifies the changes. Tested this locally, we're getting events like:
```
8m         Normal    OperatorStatusChanged        deployment/openshift-kube-scheduler-operator               Status for clusteroperator/kube-scheduler changed: Degraded message changed from "" to "Degraded: Forced Error"
10m         Normal    OperatorStatusChanged        deployment/openshift-kube-scheduler-operator               Status for clusteroperator/kube-scheduler changed: Degraded message changed from "Degraded: Forced Error" to ""
```
> Remove degraded

- pkg/operator/staleconditions/remove_stale_conditions.go
- pkg/operator/starter.go
To remove a degraded status, you need to remove the degraded==true condition that was set by accident in 4.1.0.  Otherwise, new clusters will be fine, but old cluster will stay degraded.
/assign @ravisantoshgudimetla
> remove stale condition set by accident in 4.1.0

- bindata/v3.11.0/kube-scheduler/servicemonitor.yaml
- pkg/operator/v311_00_assets/bindata.go
Since each team should own their monitoring configuration we are removing ServiceMonitor manifests from cluster-monitoring-operator.
Related to openshift/cluster-monitoring-operator#391
/cc @brancz @sttts
> manifests: add ServiceMonitor for kube-scheduler

- bindata/v3.11.0/kube-scheduler/ns.yaml
- manifests/0000_90_kube-scheduler-operator_04_servicemonitor-scheduler.yaml
- pkg/operator/v311_00_assets/bindata.go
Move incorrectly placed ServiceMonitor manifest from `bindata/` into `manifests/`.
This is modeled after similar design in https://github.com/openshift/cluster-kube-apiserver-operator
Should unblock https://github.com/openshift/cluster-monitoring-operator/pull/391
/cc @sttts @s-urbaniak
> move kube-scheduler servicemonitor to manifests

- pkg/operator/configobservation/scheduler/observe_scheduler.go
- pkg/operator/configobservation/scheduler/observe_scheduler_test.go
Harcoded configmap name should be used instead of configmap name we get from scheduler CR.
/cc @damemi
> Fix to have hardcoded configmap name in the scheduler config

- pkg/operator/configmetrics/configmetrics.go
- pkg/operator/starter.go
This adds metrics reporting to the kube-scheduler operator, specifically it will report a 1 or 0 for if masters are schedulable under the metric `cluster_master_schedulable`
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1749457
> Bug 1749457: Add master_schedulable metric

- pkg/operator/target_config_reconciler.go
Reducing the number of syncs of TargetConfigReconciler to half.
Rates reduced to:
* configmaps: ~2
* rolebindings: ~1
* secrets: ~0.5
> Bug 1745671: Do not register event handlers twice for configmaps under openshift-kube-scheduler

- manifests/0000_90_kube-scheduler-operator_04_servicemonitor-scheduler.yaml
- pkg/operator/configmetrics/configmetrics.go
* First commit will make metrics collection from scheduler secure
* Second commit will switch to use `legacyregistry` for metrics collection
> Fix scheduler metrics

- manifests/0000_25_kube-scheduler-operator_02_service.yaml
- manifests/0000_25_kube-scheduler-operator_06_deployment.yaml
- manifests/0000_25_kube-scheduler-operator_07_clusteroperator.yaml
- manifests/0000_90_kube-scheduler-operator_03_servicemonitor.yaml
- manifests/0000_90_kube-scheduler-operator_04_servicemonitor-scheduler.yaml
Enables the CVO to exclude manifests in an externally hosted control plane deployment
See https://github.com/openshift/cluster-version-operator/pull/252
> Add manifest annotations for hosted deployment exclusions

- bindata/v4.1.0/kube-scheduler/kubeconfig-cert-syncer.yaml
- bindata/v4.1.0/kube-scheduler/localhost-recovery-client-crb.yaml
- bindata/v4.1.0/kube-scheduler/localhost-recovery-sa.yaml
- bindata/v4.1.0/kube-scheduler/localhost-recovery-token.yaml
- bindata/v4.1.0/kube-scheduler/pod.yaml
- cmd/cluster-kube-scheduler-operator/main.go
- pkg/operator/starter.go
- pkg/operator/target_config_reconciler.go
- pkg/operator/target_config_reconciler_v410_00.go
- pkg/operator/v410_00_assets/bindata.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_cmd.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_controller.go
- vendor/modules.txt
kube-scheduler is required to be operational if we are starting after downtime or after cert regeneration and all the regular pods are down. There is no operator to create new installer pods so we need scheduler up first. That also means it has to be able to reload refreshed certs. Kubelet also needs sdn to be running for installer pods to work as they use service network and sdn needs scheduler to run.
/hold
this needs client cert reload in origin first https://github.com/openshift/origin/pull/24646
/cc @deads2k @soltysh
> Bug 1810008: Add cert syncer

- bindata/v4.1.0/kube-scheduler/pod.yaml
- pkg/operator/v410_00_assets/bindata.go
The ks uses less than 1% of master CPU in a reasonable medium
sized workload. The ks can be bursty in certain scenarios.
Given a 1 core per master baseline (since CPU is compressible and
shared), assign the ks roughly 1.5% of that core on each master
(1/20 of the kube-apiserver usage).
> Bug 1812583: Normalize CPU requests on masters

- pkg/operator/target_config_reconciler_v410_00.go
Fixes https://github.com/openshift/cluster-kube-scheduler-operator/issues/231
Many critical spots in the scheduler code log at level `V(10)`, which is higher than our current `TraceAll` standard of 8. That means that in order to get certain helpful messages, developers currently need to manually hack the scheduler deployment to pass a `--v=10` flag which is not ideal when they could just use the loglevel setting in the operator spec.
Examples of these logs are:
* Node scores when prioritizing: https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/core/generic_scheduler.go#L650-L654
* Several plugins' debugging information:
* https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/plugins/volumezone/volume_zone.go#L167
* …
> Bump TraceAll log level to v=10

- pkg/operator/configmetrics/configmetrics.go
This adds a boolean metric for if the operator has a default node selector configured
> Add default node selector metric

- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
- pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
Currently if we add a feature gate to the `featuregates.config.openshift.io/cluster` object, the _controller-manager_ and the _apiserver_ correctly enable the feature, but the scheduler does not.
This patch adds the missing code that handles this functionality.
> Parse CustomNoUpgrade feature gates

- bindata/bootkube/config/bootstrap-config-overrides.yaml
- bindata/v4.1.0/config/defaultconfig-postbootstrap.yaml
- bindata/v4.1.0/config/defaultconfig.yaml
- pkg/operator/configobservation/scheduler/observe_scheduler.go
- pkg/operator/configobservation/scheduler/observe_scheduler_test.go
- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
- pkg/operator/v410_00_assets/bindata.go
- test/e2e/scheduler_test.go
(Note: This is a 1.19 blocker, see https://github.com/openshift/cluster-kube-scheduler-operator/issues/197)
The scheduler has changed from the old style of config ("Policy", which was based on Predicates and Priorities) to a new config API ("ComponentConfig", which is based on Plugins such as Filter and Score). The Policy API is officially deprecated, and will eventually be removed entirely.
Our operator currently parses Policy configs (as created in [this docs example](https://docs.openshift.com/container-platform/4.1/nodes/scheduling/nodes-scheduler-default.html)) and adds a reference to the Policy config in the `KubeSchedulerConfiguration`, which combines Predicate/Priority config with overall scheduler config.
We will be able to follow a similar approach once we have fully migrated to …
> Switch to v1beta1 Scheduler config to bridge between Policy/Plugin APIs

- pkg/operator/resourcesynccontroller/resourcesynccontroller.go
- pkg/operator/starter.go
- test/e2e/scheduler_test.go
Copy pasting `openshift-config/CMName` to `openshift-kube-scheduler/policy-configmap` is already carried out in the [config observer code](https://github.com/openshift/cluster-kube-scheduler-operator/blob/2f782886a6ffb61e52c9c0aa5d8dc842eb85125f/pkg/operator/configobservation/scheduler/observe_scheduler.go#L47-L52). Also, resource sync controller only copy pastes the user specified config when it's `policy-configmap` named (`SyncConfigMap` has the first argument as a destination. the second one as a source).
> Drop code that expects the config map in openshift-config namespace to have policy-configmap name

- test/e2e/scheduler_test.go
Extends the timeout for the prometheus e2e to 3 minutes (up from 30s).
This test is continuously timing out but eventually passes in CI runs,
so this is an attempt to stabilize its pass rate.
> Extend Prometheus E2E timeout

- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/status/version.go
- vendor/modules.txt
proof of openshift/library-go#865
> bump to delay version update until operand updated

- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
- vendor/modules.txt
* openshift/library-go@35b150a9: pkg/manifest: Delegate to update-approvers
* openshift/library-go@d37e5538: csi: report Available and Progressin conditions in credentialsrequestcontroller
* openshift/library-go@0d21ea36: pkg/verify: Delegate to update-approvers
* openshift/library-go@29a26d30: bump(crypto) to pick up openpgp
* openshift/library-go@c43c2cb2: Create a resuable verify package for image release verification
* openshift/library-go@2e4ba913: static-pod-installer: recreate installers that disappeared
> Bug 1858763: bump(*): vendor update

- Dockerfile.rhel7
Updating ose-cluster-kube-scheduler-operator builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/ose-cluster-kube-scheduler-operator.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.
> Updating ose-cluster-kube-scheduler-operator builder & base images to be consistent with ART

- bindata/bootkube/bootstrap-manifests/kube-scheduler-pod.yaml
- bindata/v4.1.0/kube-scheduler/pod.yaml
- pkg/operator/v410_00_assets/bindata.go
Based on https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy we should always set `dnsPolicy: ClusterFirstWithHostNet` when we have `hostNetwork: true`. 
/assign @damemi
> Bug 1889308: Set dnsPolicy ClusterFirstWithHostNet to match hostNetwork

- bindata/bootkube/bootstrap-manifests/kube-scheduler-pod.yaml
- bindata/v4.1.0/kube-scheduler/pod.yaml
- pkg/operator/v410_00_assets/bindata.go
This reverts commit 3ef0d47ec29778ad15c42aef50f33025a44dd0b1 (#293) which is causing that our static pods have in-cluster dns server injected (see https://github.com/kubernetes/kubernetes/blob/442a69c3bdf6fe8e525b05887e57d89db1e2f3a5/pkg/kubelet/network/dns/dns.go#L348-L352), which is problematic during upgrades. I'm talking with the node team how and if this is going to be solved in kubelet. 
/assign @damemi
> Revert "Set dnsPolicy ClusterFirstWithHostNet to match hostNetwork"

- bindata/v4.1.0/kube-scheduler/pod.yaml
- cmd/cluster-kube-scheduler-operator/main.go
- pkg/cmd/recoverycontroller/cmd.go
- pkg/operator/resourcesynccontroller/resourcesynccontroller.go
- pkg/operator/v410_00_assets/bindata.go
New client certs are regenerated by `kube-apiserver-regeneration-controller` into `openshift-config-managed` namespace but kube-scheduler is missing a resource sync loop for transferring them to `openshift-kube-scheduler` namespace.
This PR adds a controller to sync that client-cert-key as static pod sidecar.
Workaround for the issue:
```
oc patch secret -n openshift-kube-scheduler kube-scheduler-client-cert-key -p '{"data": {"tls.crt": "'$( oc get secret -n openshift-config-managed kube-scheduler-client-cert-key --template='{{index .data "tls.crt"}}' )'", "tls.key": "'$( oc get secret -n openshift-config-managed kube-scheduler-client-cert-key --template='{{index .data "tls.key"}}' )'"}}'
```
/cc @soltysh
> Bug 1881322: Sync new kube-scheduler-client-cert-key on recovery

- manifests/0000_25_kube-scheduler-operator_00_namespace.yaml
- manifests/0000_25_kube-scheduler-operator_02_operator.cr.yaml
- manifests/0000_25_kube-scheduler-operator_02_service.yaml
- manifests/0000_25_kube-scheduler-operator_03_configmap.yaml
- manifests/0000_25_kube-scheduler-operator_04_clusterrolebinding.yaml
- manifests/0000_25_kube-scheduler-operator_05_serviceaccount.yaml
- manifests/0000_25_kube-scheduler-operator_06_deployment.yaml
- manifests/0000_25_kube-scheduler-operator_07_clusteroperator.yaml
- manifests/0000_90_kube-scheduler-operator_01_prometheusrole.yaml
- manifests/0000_90_kube-scheduler-operator_02_prometheusrolebinding.yaml
- manifests/0000_90_kube-scheduler-operator_03_servicemonitor.yaml
- manifests/0000_90_kube-scheduler-operator_04_servicemonitor-scheduler.yaml
This partially implements phase 1 of https://github.com/openshift/enhancements#482
and does not change behavior. Initially, all cluster-kube-scheduler-operator
manifests are included in the single-node-developer cluster profile.
Follow-on PRs may exclude any of these that are not needed in the
profile.
> Annotate manifests for single-node-developer cluster profile

- bindata/v4.1.0/kube-scheduler/pod.yaml
- pkg/operator/v410_00_assets/bindata.go
> Bug 1905327: specify cpu and memory resources for initContainers

- manifests/0000_90_kube-scheduler-operator_04_servicemonitor-scheduler.yaml
- test/e2e/scheduler_test.go
As part of KEP 1916, resource consumption from pods will be tracked by the scheduler and reported. This commit will allow that endpoint to be scraped once that code is available.  This enables those metrics to be scraped.  It adds roughly 1 series per pod on average (pods usually declare ~1 resource request on average).
From the e2e run, showing the sum of requested resources for the cluster
Subsequent releases will add resource capacity dashboards.
> Bug 1907998: Collect /metrics/resources from scheduler

- bindata/v4.1.0/kube-scheduler/pod.yaml
- pkg/operator/v410_00_assets/bindata.go
This changes the recovery-controller port to `11443`, to avoid conflicting with the router
> Bug 1908145: Change recovery-controller port to avoid conflicts

- manifests/0000_90_kube-scheduler-operator_04_servicemonitor-scheduler.yaml
@smarterclayton @wking @fabiand 
https://github.com/openshift/cluster-kube-scheduler-operator/pull/283 added a resource without profile annotations.
https://github.com/openshift/oc/pull/663 will prevent this from happening again.
In fact, it was the CI run on this PR that caught this
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_oc/663/pull-ci-openshift-oc-master-images/1349103979241410560/build-log.txt
> Bug 1891068: manifests: add missing profile annotations

- bindata/v4.1.0/kube-scheduler/pod.yaml
- pkg/operator/v410_00_assets/bindata.go
Insecure port 10251 is getting removed in 1.21 in favor of secure port 10259
> bug 1889488: Have probes listen to secure ports

- bindata/v4.1.0/kube-scheduler/pod.yaml
- pkg/operator/v410_00_assets/bindata.go
"ss" shows sockets in CLOSE-WAIT state, so it's more accurate.
Following on https://github.com/openshift/cluster-kube-scheduler-operator/pull/252
CC @soltysh
> bug 1920509: Use ss instead of lsof when waiting for ports

- pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
- pkg/operator/configobservation/interfaces.go
- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
- vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/listers.go
- vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/observe_audit.go
- vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/observe_cors.go
- vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/observe_tlssecurityprofile.go
- vendor/modules.txt
By allowing to set the ciphers, KS does not have to use the default ciphers some of which may contain security vulnerabilities.
> bug 1844989: Allow to set --tls-cipher-suites and --tls-min-version of KS instances through observed config

- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
In case `servingInfo.[cipherSuites|minTLSVersion]` do not exist under observedConfig bits
> bug 1844989: Set --tls-cipher-suites, resp. --tls-min-version only when the fields under servingInfo observedConfig are found

- Makefile
- test/e2e-preferred-host/ks_preferred_host_kas_test.go
I'm going to implement it later. For now, I need it as it is to define a new CI job.
The new tests can be run directly from command line `make test-e2e-preferred-host`
> defines test-e2e-preferred-host job for running smoke tests to check if KS talks to Kube over a preferred host

- manifests/0000_90_kube-scheduler-operator_04_servicemonitor-scheduler.yaml
The tenancy proxy does not allow someone to fetch metrics for pods
unless they are namespace labelled. This is also a usability improvement
for end users.
> servicemonitor: Relabel kube_pod_resource_* pod/namespace labels

- bindata/bootkube/bootstrap-manifests/kube-scheduler-pod.yaml
- bindata/bootkube/manifests/00_openshift-kube-scheduler-ns.yaml
- bindata/v4.1.0/kube-scheduler/ns.yaml
- bindata/v4.1.0/kube-scheduler/pod.yaml
- manifests/0000_25_kube-scheduler-operator_00_namespace.yaml
- manifests/0000_25_kube-scheduler-operator_06_deployment.yaml
- pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_1.yaml
- pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_2.yaml
- pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_3.yaml
- pkg/operator/v410_00_assets/bindata.go
In support of the workload partitioning feature
(https://github.com/openshift/enhancements/pull/703), we need to add
annotations to all management pods and namespaces so they can be
properly identified and assigned to segregated management cores on
clusters configured to do so.
> Add management workload annotations

- bindata/bootkube/bootstrap-manifests/kube-scheduler-pod.yaml
- bindata/v4.1.0/kube-scheduler/pod.yaml
- manifests/0000_25_kube-scheduler-operator_06_deployment.yaml
- pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_1.yaml
- pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_2.yaml
- pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_3.yaml
- pkg/operator/v410_00_assets/bindata.go
As per https://github.com/openshift/enhancements/pull/739, the workload
annotations names are changing.
Signed-off-by: Jim Ramsay <jramsay@redhat.com>
/hold
Hold until after openshift/kubernetes#632 is merged please
> Rename workload annotations

- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/file_utils.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/prune/cmd.go
- vendor/modules.txt
As of today, the dynamic certificates i.e. `kube-apiserver-certs` are accessed by at least two processes, namely the installer pod and the cert-syncer.
Up until now, there was no coordination between these processes that might have lead to many unexpected errors, like https://bugzilla.redhat.com/show_bug.cgi?id=1963730
This PR writes all certificates in an atomic way by first creating a temporary file, writing the content to it, and then renaming it to the original file. 
`os.Rename` calls `syscall.Rename` which in turn uses the rename syscall (Linux) which provides atomicity (https://man7.org/linux/man-pages/man2/rename.2.html)
The previous attempt didn't work as it would break the DR scripts - https://github.com/openshift/library-go/pull/1098
> Bug 1963730: kube-apiserver failed to load SNI cert and key

- manifests/0000_90_kube-scheduler-operator_03_servicemonitor.yaml
Alert users about usage of deprecated scheduler policy API and its removal in 4.10
https://issues.redhat.com/browse/WRKLDS-316
> Fire SchedulerLegacyPolicySet alert when the legacy scheduler policy API is set

- manifests/0000_90_kube-scheduler-operator_03_servicemonitor.yaml
- manifests/0000_90_kube-scheduler-operator_04_servicemonitor-scheduler.yaml
The CMO is now capable of using client cert auth to scrape the metrics endpoints. Use that in our components to reduce API load and allow metrics collection when the API is down - given further authz conditions are met.
> Bug 1986829: metrics: use client cert auth for metrics scraping

- bindata/assets/config/defaultconfig-postbootstrap-highnodeutilization.yaml
- bindata/assets/config/defaultconfig-postbootstrap-lownodeutilization.yaml
- bindata/assets/config/defaultconfig-postbootstrap-noscoring.yaml
- bindata/assets/config/defaultconfig.yaml
- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
- pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
This sets default LeaderElection values to better handle API server disruption as recommended in https://github.com/openshift/enhancements/blob/master/CONVENTIONS.md#handling-kube-apiserver-disruption
> Bug 1984608: Set kube-scheduler leader election defaults

- bindata/assets/kube-scheduler/ns.yaml
Starting with OpenShift 4.10 we are introducing PodSecurity admission (https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/2579-psp-replacement).
Currently, all pods are marked as privileged, however, over time we want to enforce at least baseline, admirably restricted as default. In order not to break control plane workloads this allows workloads in `openshift-kube-scheduler` namespace to run privileged pods.
See https://github.com/openshift/enhancements/pull/899 for more details (and excuse the eventual consistency of updates).
/cc @stlaz
> podsecurity: enforce privileged for openshift-kube-scheduler namespace

- bindata/assets/config/defaultconfig-postbootstrap-highnodeutilization.yaml
This will likely need to be backported
This profile disables `LeastAllocated` but it does not disable `BalancedAllocation`. It also is setting `MostAllocated` with a weight of `0` (see https://bugzilla.redhat.com/show_bug.cgi?id=2002300#c4)
> Bug 2002300: Disable balancedAllocation and add weight for HighNodeUtilization profile

- cmd/cluster-kube-scheduler-operator/main.go
- go.mod
- go.sum
- pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
- vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
- vendor/github.com/openshift/library-go/pkg/operator/events/recorder.go
- vendor/github.com/openshift/library-go/pkg/operator/events/recorder_in_memory.go
- vendor/github.com/openshift/library-go/pkg/operator/events/recorder_logging.go
- vendor/github.com/openshift/library-go/pkg/operator/events/recorder_upstream.go
- vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/interfaces.go
- vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/prune/cmd.go
- vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
- vendor/modules.txt
```
2021-11-03T04:25:43.102203390Z F1103 04:25:43.102194       1 cmd.go:48] lstat /etc/kubernetes/static-pod-resources/kube-scheduler-certs: no such file or directory
2021-11-03T04:25:43.194947275Z goroutine 1 [running]:
2021-11-03T04:25:43.194947275Z k8s.io/klog/v2.stacks(0xc000012001, 0xc0001c81c0, 0x84, 0xda)
2021-11-03T04:25:43.194947275Z     k8s.io/klog/v2@v2.9.0/klog.go:1026 +0xb9
2021-11-03T04:25:43.194947275Z k8s.io/klog/v2.(*loggingT).output(0x3a8bd60, 0xc000000003, 0x0, 0x0, 0xc0003c81c0, 0x1, 0x2f628ac, 0x6, 0x30, 0x414600)
2021-11-03T04:25:43.194947275Z     k8s.io/klog/v2@v2.9.0/klog.go:975 +0x1e5
2021-11-03T04:25:43.194947275Z k8s.io/klog/v2.(*loggingT).printDepth(0x3a8bd60, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc000496910, 0x1, 0x1)
2021-11-03T04:25:43.194947275Z …
```
> bug 2026352: Sync with library-go to pick fixes for pruner panic

- README.md
- bindata/assets/config/defaultconfig-postbootstrap-highnodeutilization.yaml
Based on https://kubernetes.io/docs/reference/scheduling/config/#scheduler-configuration-migrations
and https://github.com/kubernetes/enhancements/tree/master/keps/sig-scheduling/2458-node-resource-score-strategy#summary
both NodeResourcesLeastAllocated and NodeResourcesMostAllocated plugins
were removed from v1beta2 and replaced with NodeResourcesFit.
> bug 2035927: Replace NodeResourcesLeastAllocated/NodeResourcesMostAllocated plugins with NodeResourcesFit

- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
The scheduler's Policy api was removed in 1.23, see https://github.com/kubernetes/kubernetes/pull/105828
As an alternative we could also keep just using the default (lownodeutilization) here, in order to not break the scheduler on upgrades. In that case, log a message that we're using the default profile instead. Open to ideas
> Bug 2033751: Return Error when trying to use Scheduler Policy

- bindata/assets/config/defaultconfig-postbootstrap-highnodeutilization.yaml
- bindata/assets/config/defaultconfig-postbootstrap-lownodeutilization.yaml
- bindata/assets/config/defaultconfig-postbootstrap-noscoring.yaml
- bindata/assets/config/defaultconfig.yaml
- bindata/bootkube/config/bootstrap-config-overrides.yaml
Bumping to kubeSchedulerConfig v1beta3 api which is default in kube1.23
cc @damemi @ingvagabund
> Bug 2039414: Update KubeSchedulerConfig to v1beta3(default in 1.23)

- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
- pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
Extending https://github.com/openshift/cluster-kube-scheduler-operator/pull/400 to remove the `PolicyUpgradeable` condition when the policy name field was previously set but cleared later on.
> bug 2037665: Remove policy upgradeable when policy field cleared

- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
From the logs:
```
I0125 06:13:50.166765       1 status_controller.go:211] clusteroperator/kube-scheduler diff {"status":{"conditions":[{"lastTransitionTime":"2022-01-25T05:43:31Z","message":"NodeControllerDegraded: All master nodes are ready","reason":"AsExpected","status":"False","type":"Degraded"},{"lastTransitionTime":"2022-01-25T06:13:50Z","message":"NodeInstallerProgressing: 3 nodes are at revision 8; 0 nodes have achieved new revision 9","reason":"NodeInstaller","status":"True","type":"Progressing"},{"lastTransitionTime":"2022-01-25T05:45:45Z","message":"StaticPodsAvailable: 3 nodes are active; 3 nodes are at revision 8; 0 nodes have achieved new revision 9","reason":"AsExpected","status":"True","type":"Available"},{"lastTransitionTime":"2022-01-25T06:13:42Z","message":"PolicyUpgrad …
```
> bug 2037665: Check policy name field independently of the configmap change

- bindata/assets/kube-scheduler/pod.yaml
- pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_1.yaml
- pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_2.yaml
- pkg/operator/targetconfigcontroller/testdata/ks_pod_scenario_3.yaml
The insecure port 10251 was removed from the kube-scheduler codebase.
> Do not wait for a port which is no longer used by the scheduler

- bindata/assets/config/defaultconfig.yaml
This commit ensures that the configmapleases are used for acquiring locks
> Update resourcelock to configmapleases

- bindata/assets/config/defaultconfig-postbootstrap-highnodeutilization.yaml
backport of https://github.com/openshift/cluster-kube-scheduler-operator/pull/378
> [release-4.9] Bug 2026109: Disable balancedAllocation and add weight for HighNodeUtilization profile

- bindata/v4.1.0/config/defaultconfig-postbootstrap-highnodeutilization.yaml
- pkg/operator/v410_00_assets/bindata.go
Backport of https://github.com/openshift/cluster-kube-scheduler-operator/pull/378
> [release-4.8] Bug 2026110: Disable balancedAllocation and add weight for HighNodeUtilization profile

- manifests/0000_25_kube-scheduler-operator_06_deployment.yaml
Starting from OpenShift 4.11 pod security admission is being activated. In OpenShift the default pod security admission level is going to be `restricted`. This PR fixes workloads from this repository. Concretely, the following violations have been detected:
```
{
  "objectRef": "openshift-kube-scheduler-operator/deployments/openshift-kube-scheduler-operator",
  "pod-security.kubernetes.io/audit-violations": "would violate PodSecurity \"restricted:latest\": allowPrivilegeEscalation != false (container \"kube-scheduler-operator-container\" must set securityContext.allowPrivilegeEscalation=false), unres
tricted capabilities (container \"kube-scheduler-operator-container\" must set securityContext.capabilities.drop=[\"ALL\"]), runAsNonRoot != true (pod or container …
```
> manifests/deployment: comply to restricted pod security level

- bindata/bootkube/config/bootstrap-config-overrides.yaml
Previously we used to rely on configmaps for leader election. Starting 4.10 we switched to configmapsleases and this was updated in the scheduler config. This is causing bootstrap scheduler to use configmaps where as the newly created scheduler to use configmapsleases causing 2 schedulers(bootstrap scheduler + newly created scheduler) to run at the same time.
For a sample bootstrap scheduler log which failed:
```
apiVersion: kubescheduler.config.k8s.io/v1beta3
clientConnection:
acceptContentTypes: ""
burst: 100
contentType: application/vnd.kubernetes.protobuf
kubeconfig: /etc/kubernetes/secrets/kubeconfig
qps: 50
enableContentionProfiling: true
enableProfiling: true
kind: KubeSchedulerConfiguration
leaderElection:
leaderElect: true
leaseDuration: 15s
renewDeadline: 10s
resourceLock: …
```
> Bug 2062459: Fix bootstrap leader election config

- .ci-operator.yaml
- Dockerfile.rhel7
- go.mod
- pkg/operator/configobservation/scheduler/observe_scheduler.go
- pkg/operator/configobservation/scheduler/observe_scheduler_test.go
Built on top of https://github.com/openshift/cluster-kube-scheduler-operator/pull/439
> Bump go.mod golang version to 1.19

- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/config/serving/server.go
- vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
- vendor/modules.txt
[Trt-589](https://issues.redhat.com//browse/Trt-589) is researching an issue where installer pods timeout, shutdown and enter a failed state triggering KubePodNotReady alerts.  library-go was updated to add milestone logging to track the progress and track down the issue.  Bumping the version to pull those changes in.
> trt-589 bump library-go

- bindata/bootkube/bootstrap-manifests/kube-scheduler-pod.yaml
- go.mod
- go.sum
- pkg/test/assets_test.go
- vendor/github.com/openshift/library-go/pkg/assets/assets.go
- vendor/github.com/openshift/library-go/pkg/crypto/OWNERS
- vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
- vendor/github.com/openshift/library-go/pkg/operator/render/options/generic.go
- vendor/github.com/openshift/library-go/pkg/operator/render/render.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/OWNERS
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installerstate/installer_state_controller.go
- vendor/modules.txt
To avoid:
```
Oct 28 23:58:55.693391 ci-op-3hj6pnwf-4f6ab-lv57z-master-1 kubenswrapper[1657]: E1028 23:58:55.693346    1657 kubelet_pods.go:413] "Hostname for pod was too long, truncated it" podName="openshift-kube-scheduler-guard-ci-op-3hj6pnwf-4f6ab-lv57z-master-1" hostnameMaxLen=63 truncatedHostname="openshift-kube-scheduler-guard-ci-op-3hj6pnwf-4f6ab-lv57z-maste"
Oct 28 23:59:03.735726 ci-op-3hj6pnwf-4f6ab-lv57z-master-0 kubenswrapper[1670]: E1028 23:59:03.735671    1670 kubelet_pods.go:413] "Hostname for pod was too long, truncated it" podName="openshift-kube-scheduler-guard-ci-op-3hj6pnwf-4f6ab-lv57z-master-0" hostnameMaxLen=63 truncatedHostname="openshift-kube-scheduler-guard-ci-op-3hj6pnwf-4f6ab-lv57z-maste"
Oct 28 23:59:11.168082 ci-op-3hj6pnwf-4f6ab-lv57z-master-2 …
```
> OCPBUGS-3041: guard controller: set an explicit hostname to avoid name collisions

- bindata/bootkube/bootstrap-manifests/kube-scheduler-pod.yaml
These flags were removed in https://github.com/kubernetes/kubernetes/pull/112120, based on [the defaults](https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components/README.md#logging-defaults)  we should be good with just dropping these flags.
> Drop flags removed in k8s 1.26

- bindata/bootkube/bootstrap-manifests/kube-scheduler-pod.yaml
Followup to https://github.com/openshift/cluster-kube-apiserver-operator/pull/1420
> Drop log flags removed in k8s 1.26

- bindata/bootkube/bootstrap-manifests/kube-scheduler-pod.yaml
This results in historical log files being wiped on restart
This reverts commit 2d66da34ffea52fe012677d9e62a65ad6f080007.
> Revert "Drop log flags removed in k8s 1.26"

- bindata/bootkube/bootstrap-manifests/kube-scheduler-pod.yaml
Previously deprecated klog flags will be removed completely in kube 1.26.
Logs of bootstrap pods were previously using the --log-file flag, will be available in the cri-o container logs instead.
> remove use of deprecated klog flags

- bindata/bootkube/bootstrap-manifests/kube-scheduler-pod.yaml
- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
- vendor/modules.txt
Backporting https://github.com/openshift/cluster-kube-scheduler-operator/pull/446
> OCPBUGS-4551: guard controller: set an explicit hostname to avoid name collisions

- bindata/assets/config/defaultconfig.yaml
- bindata/bootkube/config/bootstrap-config-overrides.yaml
disable debug pporf with unauthenticated port for ocp 4.12
has resolved in https://github.com/openshift/cluster-kube-scheduler-operator/pull/468, should backporting to both 4.13 and 4.12
> OCPBUGS-14652: disable debug pporf with unauthenticated port for 4.12

- bindata/assets/config/defaultconfig-postbootstrap-highnodeutilization.yaml
- bindata/assets/config/defaultconfig-postbootstrap-lownodeutilization.yaml
- bindata/assets/config/defaultconfig-postbootstrap-noscoring.yaml
- bindata/assets/config/defaultconfig.yaml
- bindata/bootkube/config/bootstrap-config-overrides.yaml
https://github.com/kubernetes/kubernetes/pull/119994/ removes `kubescheduler.config.k8s.io/v1beta3` entirely, and this will prevent us from running k8s 1.29. `kubescheduler.config.k8s.io/v1` is available since 1.25.
/assign @ingvagabund
> OCPNODE-1886: Migrate from kubescheduler.config.k8s.io/v1beta3 to v1

- go.mod
- go.sum
- pkg/operator/starter.go
- vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/observe_tlssecurityprofile.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
- vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/manifests/guard-pod.yaml
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
- vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
- vendor/modules.txt
- revision_controller: be more verbose about LatestAvailableRevision and resourceVersion
- add pdbUnhealthyPodEvictionPolicy option to a GuardController
- guard: add workload partitioning annotation
> OCPBUGS-23463: bump(library-go)

- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/manifests/guard-pod.yaml
- vendor/modules.txt
Pulling https://github.com/openshift/library-go/pull/1602
> OCPBUGS-27065: bump(library-go)=release-4.13

- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/manifests/guard-pod.yaml
- vendor/modules.txt
Pulling https://github.com/openshift/library-go/pull/1602
> OCPBUGS-27067: bump(library-go)=release-4.12

- Dockerfile.rhel7
- go.mod
> OCPBUGS-34367: Updating ose-cluster-kube-scheduler-operator-container image to be consistent with ART for 4.17

- .ci-operator.yaml
- Dockerfile.ocp
- go.mod
Reconciling with https://github.com/openshift/ocp-build-data/tree/a39508c86497b4e5e463d7b2c78e51e577be9e7d/images/ose-cluster-kube-scheduler-operator.yml
Rebasing https://github.com/openshift/cluster-kube-scheduler-operator/pull/553.
> OCPBUGS-45724: Updating ose-cluster-kube-scheduler-operator-container image to be consistent with ART for 4.19

- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
- vendor/modules.txt
This is motivated by the installer controller fix in library-go.
cc @benluddy
> OCPBUGS-48700: Bump to latest library-go

- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
- pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
Use case: if the cluster admin enables `TechPreview`, which has `DynamicResourceAllocation` feature gate enabled, it should automatically enable all of DRA, including the scheduler plugin `DynamicResources`.
We shouldn't have to force the admin to do the extra step:
```
oc patch --type merge -p '{"spec":{"profile": "HighNodeUtilization", "profileCustomizations" 
{"dynamicResourceAllocation": "Enabled"}}}' scheduler cluster
```
> OCPNODE-3192: enable the scheduler plugin if the feature gate DynamicResourceAllocation is enabled

- manifests/0000_25_kube-scheduler-operator_06_deployment.yaml
Fix missing readOnlyRootFilesystem security context in the openshift-kube-scheduler-operator deployment.
This completes the work from PR #564 which added readOnlyRootFilesystem to the kube-scheduler pods, but missed the operator pod itself.
Changes:
- Add readOnlyRootFilesystem: true to container securityContext
- Add /tmp volume mount for temporary files
- Add tmp emptyDir volume
Fixes test failure:
'pod openshift-kube-scheduler-operator does not have readOnlyRootFilesystem'
> OCPSTRAT-2001: Add readOnlyRootFilesystem to kube-scheduler-operator
